@startuml
title Diagramme de Séquence - Inscrire un client à un cours
actor Accueil
participant Systeme
participant Compte
participant Cours
participant Client

'Connexion à un compte'
Accueil -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueil

'Séparation'
|||

'Inscrire un client à un cour par propriétaire et moniteur'
Accueil -> Systeme: inscrireClientCours()
        Systeme -> Cours : getListeCours()
        Cours --> Systeme : listeCours
        Systeme --> Accueil : afficherListeCours()
        Accueil -> Systeme : selectionnerCours(cours)
        Systeme -> Client : getListeClients()
        Client --> Systeme : listeClients
        Systeme -> Accueil : afficherListeClients()
        Accueil -> Systeme : inscrireClientCours(client)
        Systeme -> Cours : ajouterClient(client)
        return
        Systeme --> Accueil
@enduml