@startuml
title Diagramme de Séquence - Consulter le materiel
actor Accueille
participant Systeme
participant Compte
participant Materiel



'Connexion à un compte'
Accueille -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueille

'Séparation'
|||

'Accueille consulte le matériel'
Accueille -> Systeme : consulterMateriel()
    Systeme -> Materiel : getMaterielDispo()
    Materiel --> Systeme : listeMateriel
    Systeme --> Accueille : afficherListeMateriel()

@enduml