@startuml
title Diagramme de Séquence - Ajouter un partenaire
actor Proprietaire
participant Systeme
participant Compte
participant Camping

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire

'Séparation'
|||

'Ajouter un partenaire'
Proprietaire -> Systeme: afficherListePartenaires()
Systeme -> Camping: getListeCamping()
Camping --> Systeme: listeCamping
Systeme -> Proprietaire: afficherListeCamping(listeCamping)

Proprietaire -> Systeme: ajouterPartenaire(nom, réduction)
Systeme -> Camping: ajouterPartenaire(nom, réduction)
return
Camping --> Proprietaire: confirmation
@enduml