@startuml
title Diagramme de Séquence - Enregistrer un retard
actor Accueille
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Accueille -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueille

'Séparation'
|||

'Accueille'
Accueille -> Systeme: signalerRetard()
Systeme -> Materiel: enregistrerRetard()
return
Systeme --> Accueille

@enduml