@startuml
title Diagramme de Séquence - Supprimer un partenaire
actor Proprietaire
participant Systeme
participant Compte
participant Camping

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire

'Séparation'
|||

'Ajouter un partenaire'
Proprietaire -> Systeme: afficherListePartenaires()
Systeme -> Camping: obtenirListeCamping()
Camping --> Systeme: listeCamping
Systeme --> Proprietaire: afficherListeCamping()

Proprietaire -> Systeme: supprimerPartenaire(partenaire)
Systeme -> Camping: supprimerPartenaire(partenaire)
return
systeme --> Proprietaire: confirmation
@enduml