@startuml
title Diagramme de Séquence - Récupérer une caution
actor Accueil
participant Systeme
participant Compte
participant Client
participant Paiement

'Connexion à un compte'
Accueil -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueil

'Séparation'
|||

'Accueil sélectionne un client'
Accueil -> Systeme: rechercherClient()
Systeme -> Client: rechercherClient()
return listeClients
Accueil <-- Systeme: listeClients


'Séparation'
|||

'Sélection d'un client'
Accueil -> Systeme: selectionnerClient()
return Client

'Séparation'
|||

'Accueil récupère la caution'
Accueil -> Systeme: recupererCaution()
Systeme -> Client: recupererCaution()
alt Paiement réussi
Client -> Paiement: paiementCaution()
return Paiement
Systeme <-- Client: Paiement
Accueil <- Systeme: afficherMessageValidation(Paiement)

else Paiement échoué
Client -> Paiement: paiementCaution()
return Paiement
Systeme <-- Client: Paiement
Accueil <- Systeme: afficherMessageErreur(Paiement)
end

@enduml