@startuml
title Diagramme de Séquence - Encaisser un utilisateur
actor Utilisateur
participant Systeme
participant Compte
participant Paiement
participant Terminal

'Connexion à un compte'
Utilisateur -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
Compte -> Utilisateur: confirmerConnexion()

'Séparation'
|||

'Utilisateur encaisse un client'
Utilisateur -> Systeme: encaisser()
Systeme -> Paiement: creerPaiement()
Paiement --> Systeme : Paiement

'Séparation'
|||

'Utilisateur applique une reduction'
group if [Reduction à appliquer]
    Systeme -> Paiement : appliquerReduction(Paiement)
    return Paiement
end

'Séparation'
|||


alt paiement = true
Systeme -> Terminal: payer(Paiement)
return true
Systeme -> Utilisateur: confirmerEncaissement(Paiement)
|||

else paiement = false
Systeme -> Terminal: payer(Paiement)
return false
Systeme -> Utilisateur: afficherMessageErreur(Paiement)
|||
end
@enduml