@startuml
title Diagramme de Séquence - Consulter la liste des partenaires
actor Propriétaire
participant Systeme
participant Compte
participant Camping

'Connexion à un compte'
Propriétaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Propriétaire

'Séparation'
|||

'Consulter la liste des partenaires'
Propriétaire -> Systeme: consulterListePartenaires()
    Systeme -> Camping: obtenirListeCampings()
    Camping --> Systeme: listeCampings
    Systeme --> Propriétaire: afficherListePartenaires()
@enduml