@startuml
title Diagramme de Séquence - Mettre au rebus du Materiel
actor Proprietaire
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire



'Séparation'
|||


'Proprietaire consulte le matériel'
Proprietaire -> Systeme : consulterMateriel()
Systeme -> Compte : verifierDroitsAcces()
Compte --> Systeme : true
Systeme -> Materiel : getMaterielDispo()
Materiel --> Systeme : listeMateriel
Systeme --> Proprietaire : afficherListeMateriel(listeMateriel)

'Séparation'
|||

'Propriétaire met au rebus un materiel'
Proprietaire -> Systeme : mettreAuRebut(materiel)
Systeme -> Materiel : supprimerMateriel(materiel)
Systeme -> Proprietaire : envoyerConfirmation()

@enduml