@startuml
title Diagramme de Séquence - Programmer un cours
actor Proprietaire
participant Systeme
participant Compte
participant Cours

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
Compte -> Proprietaire: confirmerConnexion()

'Séparation'
|||

'Propriétaire ajoute un cours'
Proprietaire -> Systeme: ajouterCours()
Systeme -> Cours: creerCours()
Cours --> Systeme: Cours
Systeme --> Proprietaire: Cours

@enduml