@startuml
title Diagramme de Séquence - Gérer les stocks de Materiel
actor Proprietaire
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire


'Séparation'
|||


'Propriétaire Alloue du Materiel disponible'
Proprietaire -> Systeme: allouerMaterielDisponible()
Systeme -> Materiel: recupererMateriel()
Materiel --> Systeme: Materiel
Systeme --> Proprietaire: Materiel


@enduml