@startuml
title Diagramme de Séquence - Ajouter du Materiel
actor Proprietaire
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire

'Séparation'
|||

'Propriétaire ajoute un Materiel'
Proprietaire -> Systeme: ajouterMateriel()
Systeme -> Materiel: creerMateriel()
Materiel --> Systeme
Systeme --> Proprietaire

@enduml