@startuml
title Diagramme de Séquence - Consulter le materiel
actor Accueil
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Accueil -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueil

'Séparation'
|||

'Accueille consulte le matériel'
Accueil -> Systeme : consulterMateriel()
Systeme -> Materiel : getMaterielDispo()
Materiel --> Systeme : listeMateriel
Systeme --> Accueil : afficherListeMateriel(listeMateriel)

@enduml