@startuml
title Diagramme de Séquence - Récupérer une caution
actor Utilisateur
participant Systeme
participant Compte
participant Client
participant Paiement

'Connexion à un compte'
Utilisateur -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
Compte -> Utilisateur: confirmerConnexion()

'Séparation'
|||

'Utilisateur sélectionne un client'
Utilisateur -> Systeme: rechercherClient()
Systeme -> Client: rechercherClient()
return listeClients
Utilisateur <-- Systeme: listeClients


'Séparation'
|||

'Sélection d'un client'
Utilisateur -> Systeme: selectionnerClient()
return Client

'Séparation'
|||

'Utilisateur récupère la caution'
Utilisateur -> Systeme: recupererCaution()
Systeme -> Client: recupererCaution()
alt Paiement réussi
Client -> Paiement: paiementCaution()
return Paiement
Systeme <-- Client: Paiement
Utilisateur <- Systeme: afficherMessageValidation(Paiement)

else Paiement échoué
Client -> Paiement: paiementCaution()
return Paiement
Systeme <-- Client: Paiement
Utilisateur <- Systeme: afficherMessageErreur(Paiement)
end

@enduml