@startuml
title Diagramme de Séquence - Consulter la liste des partenaires
actor Accueille
participant Systeme
participant Compte
participant Camping

'Connexion à un compte'
Accueille -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueille

'Séparation'
|||

'Consulter la liste des partenaires'
Accueille -> Systeme: consulterListePartenaires()
    Systeme -> Camping: obtenirListeCampings()
    Camping --> Systeme: listeCampings
    Systeme --> Accueille: afficherListePartenaires()
@enduml