@startuml
title Diagramme de Séquence - Consulter les cours disponibles
actor Accueille as Utilisateur
participant Systeme
participant Compte
participant Cours

'Connexion à un compte'
Utilisateur -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Utilisateur

'Séparation'
|||

'Consulter les cours disponibles'
Utilisateur -> Systeme : consulterCours()
Systeme -> Cours : getCoursDispo()
Cours --> Systeme : listeCours
Systeme --> Utilisateur : afficherListeCours()

@enduml