@startuml
title Diagramme de Séquence - Inscrire un client à un cours
actor Accueille
participant Systeme
participant Compte
participant Cours
participant Client

'Connexion à un compte'
Accueille -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueille

'Séparation'
|||

'Inscrire un client à un cour par propriétaire et moniteur'
Accueille -> Systeme: inscrireClientCours()
        Systeme -> Cours : getListeCours()
        Cours --> Systeme : listeCours
        Systeme --> Accueille : afficherListeCours()
        Accueille -> Systeme : selectionnerCours(cours)
        Systeme -> Client : getListeClients()
        Client --> Systeme : listeClients
        Systeme -> Accueille : afficherListeClients()
        Accueille -> Systeme : inscrireClientCours(client)
        Systeme -> Cours : ajouterClient(client)
        return
        Systeme --> Accueille
@enduml