@startuml
'https://plantuml.com/sequence-diagram

actor "moniteur de voile" as mono

mono -> System : seConnecter()
System -> Compte : validationAuthentification()
return
System --> mono
mono -> System : consulterListeMateriel()
System -> Materiel : ObtenirMateriel()
return materiel1, materiel2, materiel3
System -> mono : afficherListeMateriel(materiel1, materiel2,materiel3)
mono -> System : déclarerPanne(materiel2)
System -> Materiel : déclarerPanne(materiel2)
return
System --> mono


@enduml