@startuml
title Diagramme de Séquence - Programmer un cours
actor Proprietaire
participant Systeme
participant Compte
participant Cours

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Proprietaire

'Séparation'
|||

'Propriétaire ajoute un cours'
Proprietaire -> Systeme: ajouterCours(12/08/2025:10:00,12/08/2025:11:30)
Systeme -> Cours: creerCours(12/08/2025:10:00,12/08/2025:11:30)
Cours --> Systeme
Systeme --> Proprietaire

@enduml