@startuml
title Diagramme de Séquence - Mettre au rebus du Materiel
actor Proprietaire
participant Systeme
participant Compte
participant Materiel

'Connexion à un compte'
Proprietaire -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
Compte -> Proprietaire: confirmerConnexion()



'Séparation'
|||


'Proprietaire consulte le matériel'
Proprietaire -> Systeme : consulterMateriel()
Systeme -> Compte : verifierDroitsAcces()
alt consultMat == true
    Compte --> Systeme : true
    Systeme -> Materiel : getMaterielDispo()
    Materiel --> Systeme : listeMateriel
    Systeme --> Proprietaire : afficherListeMateriel()
else consultMat == false
    Compte --> Systeme : false
    Systeme --> Proprietaire : afficherMessageErreur()
end

'Séparation'
|||

'Propriétaire met au rebus un materiel'
Proprietaire -> Systeme : mettre_au_rebut()
Systeme -> Materiel : supprimer_materiel()
Systeme -> Proprietaire : envoyer_confirmation()

@enduml