@startuml
title Diagramme de Séquence - Encaisser un utilisateur
actor Accueil
participant Systeme
participant Compte
participant Paiement
participant Terminal

'Connexion à un compte'
Accueil -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme --> Accueil

'Séparation'
|||

'Accueil encaisse un client'
Accueil -> Systeme: encaisser()
Systeme -> Paiement: creerPaiement()
Paiement --> Systeme : Paiement

'Séparation'
|||

'Accueil applique une reduction'
group if [Reduction à appliquer]
    Systeme -> Paiement : appliquerReduction(Paiement)
    return Paiement
end

'Séparation'
|||

'Accueille demande un paiement'
alt paiement = true
Systeme -> Terminal: payer(Paiement)
return true
Systeme -> Accueil: confirmerEncaissement(Paiement)

'Séparation'
|||

else paiement = false
Systeme -> Terminal: payer(Paiement)
return false
Systeme -> Accueil: afficherMessageErreur(Paiement)
end
@enduml