@startuml
title Diagramme de Séquence - Encaisser un utilisateur
actor Accueille
participant Systeme
participant Compte
participant Paiement
participant Terminal

'Connexion à un compte'
Accueille -> Systeme: seConnecter()
Systeme -> Compte: validationAuthentification()
return
Systeme -> Accueille

'Séparation'
|||

'Accueille encaisse un client'
Accueille -> Systeme: encaisser()
Systeme -> Paiement: creerPaiement()
Paiement --> Systeme : Paiement

'Séparation'
|||

'Accueille applique une reduction'
group if [Reduction à appliquer]
    Systeme -> Paiement : appliquerReduction(Paiement)
    return Paiement
end

'Séparation'
|||


alt paiement = true
Systeme -> Terminal: payer(Paiement)
return true
Systeme -> Accueille: confirmerEncaissement(Paiement)
|||

else paiement = false
Systeme -> Terminal: payer(Paiement)
return false
Systeme -> Accueille: afficherMessageErreur(Paiement)
|||
end
@enduml